version: '3.8'

services:
  crypto-node-grass:
    image: camislav/grass
    restart: always
    ports:
      - ${GRASS_PORT}:80
    environment:
      - GRASS_USER=${GRASS_USER}
      - GRASS_PASS=${GRASS_PASSWORD}
      - ALLOW_DEBUG=False
